---
- hosts: all
  become: true
  pre_tasks:
    - name: Install updates (Fedora)
      tags: always
      dnf:
        update_only: yes
        update_cache: yes
      when: ansible_distribution == "Fedora"

    - name: Install updates (Ubuntu/Debian)
      tags: always
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution in ["Ubuntu", "Debian"]

- hosts: workstations
  become: true
  tasks:
    - name: Install unzip
      package:
        name: unzip
    - name: Install terraform
      unarchive:
        src: https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
        dest: /usr/local/bin
        remote_src: yes
        mode: 0755
        owner: root
        group: root

- hosts: web_servers
  become: true
  tasks:
    - name: install apache and php for Ubuntu servers
      tags: apache,apache2,ubuntu,debian
      apt:
        name:
          - apache2
          - libapache2-mod-php
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: install apache and php for CentOS servers
      tags: apache,httpd,fedora
      dnf:
        name:
          - httpd
          - php
        state: latest
      when: ansible_distribution == "Fedora"

    - name: Change apache email address
      tags: apache,fedora,httpd
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: "^ServerAdmin"
        line: ServerAdmin ethan@bruning.io
      when: ansible_distribution == "Fedora"
      register: httpd

    - name: Restart httpd (Fedora)
      tags: apache,fedora,httpd
      service:
        name: httpd
        state: restarted
      when: httpd.changed

    - name: Copy default html file for site
      tags: apache,apache2,httpd
      copy:
        src: default_site.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644

    - name: Start httpd (Fedora)
      tags: apache,fedora,httpd
      service:
        name: httpd
        state: started
        enabled: yes
      when: ansible_distribution == "Fedora"

- hosts: db_servers
  become: true
  tasks:
    - name: Install mariadb package (Fedora)
      tags: fedora,db,mariab
      dnf:
        name: mariadb
        state: latest
      when: ansible_distribution == "Fedora"

    - name: Install mariadb package (Ubuntu/Debian)
      tags: db,mariadb,ubuntu,debian
      apt:
        name: mariadb-server
        state: latest
      when: ansible_distribution in ["Ubuntu", "Debian"]

- hosts: file_servers
  become: true
  tasks:
    - name: Install samba package
      tags: samba
      package:
        name: samba
        state: latest
