---
- hosts: all
  become: true
  pre_tasks:
    - name: Install updates (Fedora)
      tags: always
      dnf:
        update_only: yes
        update_cache: yes
      when: ansible_distribution == "Fedora"

    - name: Install updates (Ubuntu/Debian)
      tags: always
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution in ["Ubuntu", "Debian"]

- hosts: web_servers
  become: true
  tasks:
    - name: install apache and php for Ubuntu servers
      tags: apache,apache2,ubuntu,debian
      apt:
        name:
          - apache2
          - libapache2-mod-php
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: install apache and php for CentOS servers
      tags: apache,httpd,fedora
      dnf:
        name:
          - httpd
          - php
        state: latest
      when: ansible_distribution == "Fedora"

- hosts: db_servers
  become: true
  tasks:
    - name: Install mariadb package (Fedora)
      tags: fedora,db,mariab
      dnf:
        name: mariadb
        state: latest
      when: ansible_distribution == "Fedora"

    - name: Install mariadb package (Ubuntu/Debian)
      tags: db,mariadb,ubuntu,debian
      apt:
        name: mariadb-server
        state: latest
      when: ansible_distribution in ["Ubuntu", "Debian"]

- hosts: file_servers
  become: true
  tasks:
    - name: Install samba package
      tags: samba
      package:
        name: samba
        state: latest
